### ISSUE TITLE
TLS 1.2 support

### ISSUE THREAD

**Issue by seangenabe** [smiley22/S22.Xmpp#4]
Please add TLS 1.2 support. Currently the library only uses TLS v1.

**Comment by st-gwerner** [comment]
You can add this to the top of your application to support TLS 1.2:

using System.Net;

// snip

ServicePointManager.SecurityProtocol = SecurityProtocolType.Tls | SecurityProtocolType.Tls11 | SecurityProtocolType.Tls12;
