### ISSUE TITLE
Derive hostname from username?

### ISSUE THREAD

**Issue by tewarid** [smiley22/S22.Xmpp#6]
I wonder if this has ever come up. I'm in a situation where I try to connect with a hostname of xyz.com (for illustration purposes let's assume it's valid) but the host rejects the request (host-unknown) because it expects the stream to be initiated thus

```
<?xml version='1.0' encoding='UTF-8'?><stream:stream xmlns='jabber:client' to='abc' version='1.0' xmlns:stream='http://etherx.jabber.org/streams' xml:lang='en-GB'>
```

where abc in the to attribute is part of the JID in the username e.g. user@abc.

An IM client that I use (swift.im) allows you to specify a different server (xyz.com) and derives the hostname (using the terminology from S22.Xmpp) from the JID.

Thoughts?

**Comment by jmasseo** [comment]
This was the whole reason I ended up forking.  I no longer use this product and that project is long over for me.  It's only a few lines of code change to make that happen.

**Comment by pgstath** [comment]
If I understand correctly you should use XMPP SRV records, http://wiki.xmpp.org/web/SRV_Records, and setup correctly the XMPP server.

**Comment by tewarid** [comment]
Until the backend infrastructure gets fixed, I'll probably work around the issue by mapping "abc" to an IP address in the hosts file, and use "abc" as the hostname when initializing XmppClient.

**Comment by pgstath** [comment]
Sound solution, for a development environment! Much better than doing alchemy in the protocol level
